gameofskate_venv/src/GameOfSkate/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from personal.views import (
	no_login_view
)

from cuenta.views import (
    register_view,
    login_view,
    logout_view,
    buscar_usuarios_view,
)

urlpatterns = [
	path('', no_login_view, name='home'),
    path('cuenta/', include('cuenta.urls', namespace='cuenta')),
	path('admin/', admin.site.urls),
    path('amistad/', include('amistad.urls', namespace='amistad')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', register_view, name="register"),
    path('buscar/', buscar_usuarios_view, name="buscar"),
    path('eventos/', include('eventos.urls', namespace='eventos')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gameofskate_venv/src/amistad/urls.py
from django.urls import path

from amistad.views import(
	enviar_solicitud_amistad,
	solicitudes_amistad,
	aceptar_solicitud_amistad,
	eliminar_amigo,
	rechazar_solicitud_amistad,
	cancelar_solicitud_amistad,
	lista_amigos_view,
)

app_name = 'amistad'

urlpatterns = [
	path('lista_amigos/<user_id>', lista_amigos_view, name='lista-amigos'),
	path('eliminar_amigo/', eliminar_amigo, name='eliminar-amigo'),
    path('enviar_solicitud_amistad/', enviar_solicitud_amistad, name='enviar-solicitud-amistad'),
    path('cancelar_solicitud_amistad/', cancelar_solicitud_amistad, name='cancelar-solicitud-amistad'),
    path('solicitudes_amistad/<user_id>/', solicitudes_amistad, name='solicitudes-amistad'),
    path('aceptar_solicitud_amistad/<solicitud_amistad_id>/', aceptar_solicitud_amistad, name='aceptar-solicitud-amistad'),
    path('rechazar_solicitud_amistad/<solicitud_amistad_id>/', rechazar_solicitud_amistad, name='rechazar-solicitud-amistad'),
]

gameofskate_venv/src/cuenta/urls.py
from django.urls import path

from cuenta.views import (
	cuenta_view,
	editar_cuenta_view,
	eliminar_cuenta,
)

app_name = 'cuenta'

urlpatterns = [
	path('<user_id>/', cuenta_view, name="view"),
	path('<user_id>/editar/', editar_cuenta_view, name="editar"),
	path('eliminar_cuenta/<user_id>/', eliminar_cuenta, name='eliminar-cuenta'),
]

gameofskate_venv/src/amistad/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class ListaAmigos(models.Model):
	user	= models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user")
	amigos	= models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="amigos") 

	def __str__(self):
		return self.user.username

	def anadir_amigo(self, cuenta):
		if not cuenta in self.amigos.all():
			self.amigos.add(cuenta)
			self.save()

	def eliminar_amigo(self, cuenta):
		if cuenta in self.amigos.all():
			self.amigos.remove(cuenta)

	def actualizar_listas_amigos(self, eliminado):
		lista_amigos_propia = self

		lista_amigos_propia.eliminar_amigo(eliminado)

		lista_amigos_ajena = ListaAmigos.objects.get(user=eliminado)
		lista_amigos_ajena.eliminar_amigo(lista_amigos_propia.user)

	def son_amigos(self, amigo):
		if amigo in self.amigos.all():
			return True
		return False


class SolicitudAmistad(models.Model):
	remitente		= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="remitente")
	destinatario	= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="destinatario")
	is_active		= models.BooleanField(blank=False, null=False, default=True)
	timestamp		= models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.remitente.username

	def aceptar(self):
		destinatario_lista_amigos = ListaAmigos.objects.get(user=self.destinatario)
		if destinatario_lista_amigos:
			destinatario_lista_amigos.anadir_amigo(self.remitente)
			remitente_lista_amigos = ListaAmigos.objects.get(user=self.remitente)
			if remitente_lista_amigos:
				remitente_lista_amigos.anadir_amigo(self.destinatario)
				self.is_active = False
				self.save()

	def rechazar(self):
		self.is_active = False
		self.save()

	def cancelar(self):
		self.is_active = False
		self.save()

gameofskate_venv/src/amistad/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import json

from cuenta.models import Cuenta
from amistad.models import SolicitudAmistad, ListaAmigos


def lista_amigos_view(request, *args, **kwargs):
	context = {}
	user = request.user
	if user.is_authenticated:
		user_id = kwargs.get("user_id")
		if user_id:
			try:
				this_user = Cuenta.objects.get(pk=user_id)
				context['this_user'] = this_user
			except Cuenta.DoesNotExist:
				return HttpResponse("El usuario no existe.")
			try:
				lista_amigos = ListaAmigos.objects.get(user=this_user)
			except ListaAmigos.DoesNotExist:
				return HttpResponse(f"No se encontró una lista de amigos para {this_user.username}")
			
			if user != this_user:
				if not user in lista_amigos.amigos.all():
					return HttpResponse("No puedes ver la lista de amigos de este usuario porque no sois amigos.")
			amigos = []
			auth_user_lista_amigos = ListaAmigos.objects.get(user=user)
			for amigo in lista_amigos.amigos.all():
				amigos.append((amigo, auth_user_lista_amigos.son_amigos(amigo)))
			context['amigos'] = amigos
	else:		
		return redirect("login")

	return render(request, "amistad/lista_amigos.html", context)


def solicitudes_amistad(request, *args, **kwargs):
	context = {}
	user = request.user
	if user.is_authenticated:
		user_id = kwargs.get("user_id")
		cuenta = Cuenta.objects.get(pk=user_id)
		if cuenta == user:
			solicitudes_amistad = SolicitudAmistad.objects.filter(destinatario=cuenta, is_active=True)
			context['solicitudes_amistad'] = solicitudes_amistad
		else:
			return HttpResponse("No puedes ver las solicitudes de amistad de otros usuarios")
	else:
		redirect("login")
	return render(request, "amistad/solicitudes_amistad.html", context)


def enviar_solicitud_amistad(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "POST" and user.is_authenticated:
		user_id = request.POST.get("destinatario_user_id")
		if user_id:
			destinatario = Cuenta.objects.get(pk=user_id)
			try:
				solicitudes_amistad = SolicitudAmistad.objects.filter(remitente=user, destinatario=destinatario)
				try:
					for solicitud in solicitudes_amistad:
						if solicitud.is_active:
							raise Exception("Ya le has enviado una solicitud de amistad a este usuario.")
					solicitud_amistad = SolicitudAmistad(remitente=user, destinatario=destinatario)
					solicitud_amistad.save()
					payload['response'] = "Solicitud de amistad enviada."
				except Exception as e:
					payload['response'] = str(e)
			except SolicitudAmistad.DoesNotExist:
				solicitud_amistad = SolicitudAmistad(remitente=user, destinatario=destinatario)
				solicitud_amistad.save()
				payload['response'] = "Solicitud de amistad enviada."

			if payload['response'] == None:
				payload['response'] = "Algo ha ido mal."
		else:
			payload['response'] = "No se pudo enviar la solicitud de amistad."
	else:
		payload['response'] = "Debes estar autenticado para enviar una solicitud de amistad."
	return HttpResponse(json.dumps(payload), content_type="application/json")


def aceptar_solicitud_amistad(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "GET" and user.is_authenticated:
		solicitud_amistad_id = kwargs.get("solicitud_amistad_id")
		if solicitud_amistad_id:
			solicitud_amistad = SolicitudAmistad.objects.get(pk=solicitud_amistad_id)
			if solicitud_amistad.destinatario == user:
				if solicitud_amistad: 
					notificacion_actualizada = solicitud_amistad.aceptar()
					payload['response'] = "Solicitud de amistad aceptada."

				else:
					payload['response'] = "Algo ha ido mal."
			else:
				payload['response'] = "Esa solicitud de amistad no es para tí."
		else:
			payload['response'] = "No se pudo aceptar la solicitud de amistad."
	else:
		payload['response'] = "Debes estar autenticado para aceptar una solicitud de amistad."
	return HttpResponse(json.dumps(payload), content_type="application/json")


def eliminar_amigo(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "POST" and user.is_authenticated:
		user_id = request.POST.get("destinatario_user_id")
		if user_id:
			try:
				eliminado = Cuenta.objects.get(pk=user_id)
				lista_amigos = ListaAmigos.objects.get(user=user)
				lista_amigos.actualizar_listas_amigos(eliminado)
				payload['response'] = "Amigo eliminado con éxito."
			except Exception as e:
				payload['response'] = f"Algo ha ido mal: {str(e)}"
		else:
			payload['response'] = "No se pudo eliminar ese amigo."
	else:
		payload['response'] = "Debes estar autenticado para eliminar un amigo."
	return HttpResponse(json.dumps(payload), content_type="application/json")


def rechazar_solicitud_amistad(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "GET" and user.is_authenticated:
		solicitud_amistad_id = kwargs.get("solicitud_amistad_id")
		if solicitud_amistad_id:
			solicitud_amistad = SolicitudAmistad.objects.get(pk=solicitud_amistad_id)
			if solicitud_amistad.destinatario == user:
				if solicitud_amistad: 
					notificacion_actualizada = solicitud_amistad.rechazar()
					payload['response'] = "Solicitud de amistad rechazada."
				else:
					payload['response'] = "Algo ha ido mal."
			else:
				payload['response'] = "Esa solicitud de amistad no es para tí."
		else:
			payload['response'] = "No se pudo rechazar la solicitud de amistad."
	else:
		payload['response'] = "Debes estar autenticado para rechazar una solicitud de amistad."
	return HttpResponse(json.dumps(payload), content_type="application/json")


def cancelar_solicitud_amistad(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "POST" and user.is_authenticated:
		user_id = request.POST.get("destinatario_user_id")
		if user_id:
			destinatario = Cuenta.objects.get(pk=user_id)
			try:
				solicitudes_amistad = SolicitudAmistad.objects.filter(remitente=user, destinatario=destinatario, is_active=True)
			except SolicitudAmistad.DoesNotExist:
				payload['response'] = "La solicitud de amistad no existe."

			if len(solicitudes_amistad) > 1:
				for request in solicitudes_amistad:
					request.cance()
				payload['response'] = "Solicitud de amistad cancelada."
			else:
				solicitudes_amistad.first().cancelar()
				payload['response'] = "Solicitud de amistad cancelada."
		else:
			payload['response'] = "No se pudo cancelar la solicitud de amistad."
	else:
		payload['response'] = "Debes estar autenticado para cancelar una solicitud de amistad."
	return HttpResponse(json.dumps(payload), content_type="application/json")

gameofskate_venv/src/amistad/templates/amistad/snippets/aceptar_solicitud_amistad.html
<script type="text/javascript">
	
	function aceptarSolicitudAmistad(solicitud_amistad_id, funcionReload){
		var url = "{% url 'amistad:aceptar-solicitud-amistad' solicitud_amistad_id=53252623623632623 %}".replace("53252623623632623", solicitud_amistad_id)
		$.ajax({
			type: 'GET',
			dataType: "json",
			url: url,
			timeout: 5000,
			success: function(data) {
				if(data['response'] == "Solicitud de amistad aceptada."){
					
				} else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				alert("Algo ha ido mal.")
			},
			complete: function(data){
				funcionReload()
			}
		});
	}
	
</script>

gameofskate_venv/src/amistad/templates/amistad/snippets/cancelar_solicitud_amistad.html
<script type="text/javascript">
	
	function cancelarSolicitudAmistad(id, funcionReload){
		payload = {
			"csrfmiddlewaretoken": "{{ csrf_token }}",
			"destinatario_user_id": id,
		}
		$.ajax({
			type: 'POST',
			dataType: "json",
			url: "{% url 'amistad:cancelar-solicitud-amistad' %}",
			data: payload,
			timeout: 5000,
			success: function(data) {
				if(data['response'] == "Solicitud de amistad cancelada."){

				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				alert("Algo ha ido mal.")
			},
			complete: function(data){
				funcionReload()
			}
		});
	}
	
</script>

gameofskate_venv/src/amistad/templates/amistad/snippets/eliminar_amigo.html
<script type="text/javascript">
	
	function eliminarAmigo(id, funcionReload){
		payload = {
			"csrfmiddlewaretoken": "{{ csrf_token }}",
			"destinatario_user_id": id,
		}
		$.ajax({
			type: 'POST',
			dataType: "json",
			url: "{% url 'amistad:eliminar-amigo' %}",
			timeout: 5000,
			data: payload,
			success: function(data) {
				if(data['response'] == "Amigo eliminado con éxito."){

				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				alert("Algo ha ido mal.")
			},
			complete: function(data){
				funcionReload()
			}
		});
	}
	
</script>

gameofskate_venv/src/amistad/templates/amistad/snippets/enviar_solicitud_amistad.html
<script type="text/javascript">
	
	function enviarSolicitudAmistad(id, funcionReload){
		payload = {
			"csrfmiddlewaretoken": "{{ csrf_token }}",
			"destinatario_user_id": id,
		}
		$.ajax({
			type: 'POST',
			dataType: "json",
			url: "{% url 'amistad:enviar-solicitud-amistad' %}",
			timeout: 5000,
			data: payload,
			success: function(data) {
				if(data['response'] == "Solicitud de amistad enviada."){

				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				alert("Algo ha ido mal.")
			},
			complete: function(data){
				funcionReload()
			}
		});
	}
	
</script>

gameofskate_venv/src/amistad/templates/amistad/snippets/rechazar_solicitud_amistad.html
<script type="text/javascript">
	
	function rechazarSolicitudAmistad(solicitud_amistad_id, funcionReload){
		var url = "{% url 'amistad:rechazar-solicitud-amistad' solicitud_amistad_id=53252623623632623 %}".replace("53252623623632623", solicitud_amistad_id)
		$.ajax({
			type: 'GET',
			dataType: "json",
			url: url,
			timeout: 5000,
			success: function(data) {
				if(data['response'] == "Solicitud de amistad rechazada."){

				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				alert("Algo ha ido mal.")
			},
			complete: function(data){
				funcionReload()
			}
		});
	}
	
</script>