gameofskate_venv/src/GameOfSkate/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from personal.views import (
	no_login_view
)

from cuenta.views import (
    register_view,
    login_view,
    logout_view,
    buscar_usuarios_view,
)

urlpatterns = [
	path('', no_login_view, name='home'),
    path('cuenta/', include('cuenta.urls', namespace='cuenta')),
	path('admin/', admin.site.urls),
    path('amistad/', include('amistad.urls', namespace='amistad')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', register_view, name="register"),
    path('buscar/', buscar_usuarios_view, name="buscar"),
    path('eventos/', include('eventos.urls', namespace='eventos')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gameofskate_venv/src/cuenta/urls.py
from django.urls import path

from cuenta.views import (
	cuenta_view,
	editar_cuenta_view,
	eliminar_cuenta,
)

app_name = 'cuenta'

urlpatterns = [
	path('<user_id>/', cuenta_view, name="view"),
	path('<user_id>/editar/', editar_cuenta_view, name="editar"),
	path('eliminar_cuenta/<user_id>/', eliminar_cuenta, name='eliminar-cuenta'),
]

gameofskate_venv/src/eventos/urls.py
from django.urls import path

from eventos.views import(
	crear_evento,
	solicitudes_eventos,
	aceptar_solicitud_evento,
	rechazar_solicitud_evento,
	lista_eventos_view,
	evento_view,
	comenzar_evento,
	eliminar_evento,
)

app_name = 'eventos'
urlpatterns = [
	path('crear_evento/', crear_evento, name='crear-evento'),
	path('lista_eventos/<user_id>', lista_eventos_view, name='lista-eventos'),
    path('solicitudes_eventos/<user_id>/', solicitudes_eventos, name='solicitudes-eventos'),
    path('aceptar_solicitud_evento/<solicitud_evento_id>/', aceptar_solicitud_evento, name='aceptar-solicitud-evento'),
    path('rechazar_solicitud_evento/<solicitud_evento_id>/', rechazar_solicitud_evento, name='rechazar-solicitud-evento'),
    path('evento/<evento_id>/', evento_view, name='evento-view'),
    path('comenzar_evento/<evento_id>/', comenzar_evento, name='comenzar-evento'),
	path('eliminar_evento/<evento_id>/', eliminar_evento, name='eliminar-evento'),
]

gameofskate_venv/src/eventos/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Evento(models.Model):
    id              = models.AutoField(primary_key=True)
    nombre          = models.CharField(max_length=30)
    descripcion     = models.CharField(max_length=140, null=True, blank=True)
    creador         = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True, related_name="creador")
    participantes   = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="participantes")
    en_curso        = models.BooleanField(default=False)
    finalizado      = models.BooleanField(default=False)
    ganador         = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True, related_name="ganador")
    best_trick      = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.nombre
        
    def comenzar(self):
        self.en_curso = True
        self.save()
        solicitudes_pendientes = SolicitudEvento.objects.filter(evento=self)
        if solicitudes_pendientes:
            for solicitud in solicitudes_pendientes.all():
                if solicitud.is_active:
                    solicitud.is_active = False
                    solicitud.save()

    def finalizar(self, ganador, best_trick):
        self.ganador = ganador
        self.best_trick = best_trick
        self.en_curso = False
        self.finalizado = True
        self.save()

    def eliminar(self):
        self.delete()


class ListaEventos(models.Model):
    user	= models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="evento_user")
    eventos = models.ManyToManyField("eventos.Evento", related_name="eventos")

    def __str__(self):
        return self.user.username

    def anadir_evento(self, evento, user):
        if not evento in self.eventos.all():
            self.eventos.add(evento)
            self.save()
            evento = Evento.objects.get(id=evento.id)
            evento.participantes.add(user)
            evento.save()

    def eliminar_evento(self, evento):
        if evento in self.eventos.all():
            self.eventos.remove(evento)

    def actualizar_listas_eventos(self, evento, participantes):
        self.eliminar_evento(evento)

        for participante in participantes:
            lista_eventos_ajena = ListaEventos.objects.get(user=participante)
            lista_eventos_ajena.eliminar_evento(evento)

    def existe_evento(self, evento):
        if evento in self.eventos.all():
            return True
        return False 

class SolicitudEvento(models.Model):
    evento	    	= models.ForeignKey("eventos.Evento", on_delete=models.CASCADE, related_name=("evento_solicitud"))
    remitente	    = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="evento_remitente")
    destinatario	= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="evento_destinatario")
    is_active		= models.BooleanField(blank=False, null=False, default=True)
    timestamp		= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.remitente.username

    def aceptar(self):
        destinatario_lista_eventos = ListaEventos.objects.get(user=self.destinatario)

        if destinatario_lista_eventos:
            destinatario_lista_eventos.anadir_evento(self.evento, self.destinatario)
            self.is_active = False
            self.save()

    def rechazar(self):
        self.is_active = False
        self.save()

    def cancelar(self):
        self.is_active = False
        self.save()

gameofskate_venv/src/eventos/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from eventos.models import Evento, ListaEventos, SolicitudEvento
from eventos.utils import get_solicitudes_evento
from eventos.estado_solicitud_evento import EstadoSolicitudEvento

from amistad.models import ListaAmigos, SolicitudAmistad
from cuenta.models import Cuenta

import json

def lista_eventos_view(request, *args, **kwargs):
    context = {}
    user = request.user
    if user.is_authenticated:
        user_id = kwargs.get("user_id")
        if user_id:
            try:
                this_user = Cuenta.objects.get(pk=user_id)
                context['this_user'] = this_user
            except Cuenta.DoesNotExist:
                return HttpResponse("El usuario no existe.")
            try:
                lista_eventos = ListaEventos.objects.get(user=this_user)
            except ListaEventos.DoesNotExist:
                return HttpResponse(f"No se encontró una lista de eventos para {this_user.username}")
			
            if user != this_user:
                lista_amigos = ListaAmigos.objects.get(user=this_user)
                if not user in lista_amigos.amigos.all():
                    return HttpResponse("No puedes ver la lista de eventos de este usuario porque no sois amigos.")

            eventos_en_curso = []
            eventos_pendientes = []
            eventos_finalizados = []
            auth_user_lista_eventos = ListaEventos.objects.get(user=user)
            for evento in lista_eventos.eventos.all():
                if evento.en_curso:
                    eventos_en_curso.append(evento)
                elif evento.finalizado:
                    eventos_finalizados.append(evento)
                else:
                    eventos_pendientes.append(evento)
                    
            context['eventos_en_curso'] = eventos_en_curso
            context['eventos_pendientes'] = eventos_pendientes
            context['eventos_finalizados'] = eventos_finalizados
    else:		
        return redirect("login")
    return render(request, "eventos/lista_eventos.html", context)


def crear_evento(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated: 
        context = {}
        if request.POST:
            nombre = request.POST['nombre']
            descripcion = request.POST['descripcion']
            participantes = request.POST.getlist('participantes')
            evento = Evento.objects.create(nombre=nombre, creador=user, descripcion=descripcion)
            evento.participantes.add(user)
            evento.save()
            lista_eventos = ListaEventos.objects.get(user=user)
            lista_eventos.eventos.add(evento)
            lista_eventos.save()

            for participante in participantes:
                cuenta = Cuenta.objects.get(pk=participante)
                solicitud_evento = SolicitudEvento.objects.create(evento=evento, remitente=user, destinatario=cuenta)
                solicitud_evento.save()

            return redirect('home')
        else:
            amigos = []
            lista_amigos = ListaAmigos.objects.get(user=user)
            for amigo in lista_amigos.amigos.all():
                amigos.append(amigo)
            context['amigos'] = amigos
    else:
        redirect("login")

    return render(request, 'eventos/crear_evento.html', context)



def solicitudes_eventos(request, *args, **kwargs):
	context = {}
	user = request.user
	if user.is_authenticated:
		user_id = kwargs.get("user_id")
		cuenta = Cuenta.objects.get(pk=user_id)
		if cuenta == user:
			solicitudes_eventos = SolicitudEvento.objects.filter(destinatario=cuenta, is_active=True)
			context['solicitudes_eventos'] = solicitudes_eventos
		else:
			return HttpResponse("No puedes ver las invitaciones a eventos de otros usuarios")
	else:
		redirect("login")
	return render(request, "eventos/solicitudes_eventos.html", context)


def aceptar_solicitud_evento(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "GET" and user.is_authenticated:
		solicitud_evento_id = kwargs.get("solicitud_evento_id")
		if solicitud_evento_id:
			solicitud_evento = SolicitudEvento.objects.get(pk=solicitud_evento_id)
			if solicitud_evento.destinatario == user:
				if solicitud_evento: 
					notificacion_actualizada = solicitud_evento.aceptar()
					payload['response'] = "Invitación a evento aceptada."

				else:
					payload['response'] = "Algo ha ido mal."
			else:
				payload['response'] = "Esa invitación a evento no es para tí."
		else:
			payload['response'] = "No se pudo aceptar la invitación a evento."
	else:
		payload['response'] = "Debes estar autenticado para aceptar una invitación a evento."
	return HttpResponse(json.dumps(payload), content_type="application/json")


def rechazar_solicitud_evento(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "GET" and user.is_authenticated:
		solicitud_evento_id = kwargs.get("solicitud_evento_id")
		if solicitud_evento_id:
			solicitud_evento = SolicitudEvento.objects.get(pk=solicitud_evento_id)
			if solicitud_evento.destinatario == user:
				if solicitud_evento: 
					notificacion_actualizada = solicitud_evento.rechazar()
					payload['response'] = "Invitación a evento rechazada."
				else:
					payload['response'] = "Algo ha ido mal."
			else:
				payload['response'] = "Esa invitación a evento no es para tí."
		else:
			payload['response'] = "No se pudo rechazar la invitación a evento."
	else:
		payload['response'] = "Debes estar autenticado para rechazar una invitación a evento."
	return HttpResponse(json.dumps(payload), content_type="application/json")


def evento_view(request, *args, **kwargs):
    context = {}
    user = request.user
    context['user'] = user
    if user.is_authenticated:
        evento_id = kwargs.get("evento_id")
        if evento_id:
            try:
                evento = Evento.objects.get(id=evento_id)
            except Evento.DoesNotExist:
                return HttpResponse("El evento no existe.")
        else:
            return HttpResponse("Algo ha ido mal.")

        if request.method == "GET":
            context['evento'] = evento
            if user == evento.creador:
                es_creador = True
            else:
                es_creador = False
            context['es_creador'] = es_creador

            context['participantes'] = []
            for participante in evento.participantes.all():
                context['participantes'].append(participante)

            num_invitaciones_pendientes = SolicitudEvento.objects.filter(evento=evento).count() - evento.participantes.all().count() + 1
            context['num_invitaciones_pendientes'] = num_invitaciones_pendientes
        
        else:
            ganador_id = request.POST['ganador']
            ganador = Cuenta.objects.get(pk=ganador_id)
            best_trick = request.POST['best_trick']
            evento.finalizar(ganador, best_trick)
    else:
        return redirect("login")

    return render(request, "eventos/evento.html", context)


def comenzar_evento(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated:
        evento_id = kwargs.get('evento_id')
        evento = Evento.objects.get(id=evento_id)
        evento.comenzar()
    else:
        return redirect("login")
        
    return redirect('../../evento/'+evento_id)

def eliminar_evento(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated:
        evento_id = kwargs.get('evento_id')
        evento = Evento.objects.get(id=evento_id)
        evento.eliminar()
    else:
        return redirect("login")
        
    return redirect('../../../cuenta/'+str(user.pk))

gameofskate_venv/src/eventos/templates/eventos/crear_evento.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	.card-crear-evento {
		width: 100%;
		max-width: 400px;
		padding: 15px;
		margin: auto;
	}
	
	.form-crear-evento input[type="text"], #id_descripcion {
		margin-bottom: 10px;
		border-bottom-right-radius: 0;
		border-bottom-left-radius: 0;
	}

	
</style>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.css">
<script src="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">

<div class="container-fluid" id="id_app">
	<div class="row justify-content-center">
		<div class="card card-crear-evento">
			<div class="card-body">
				<form class="form-crear-evento" method="post">{% csrf_token %}
					<input type="text" name="nombre" id="id_nombre" class="form-control" placeholder="Nombre del evento" required>
					<textarea rows="3" name="descripcion" id="id_descripcion" class="form-control" placeholder="Descripción del evento" required></textarea>

					<div>
						<label for="id_participantes">Participantes</label>
						<select name="participantes" id="id_participantes" placeholder="Buscar amigos" multiple required>
							{% for amigo in amigos %}
							<option id="id_{{amigo.pk}}" value="{{amigo.pk}}">{{amigo.username}}</option>
							{% endfor %}
						</select>
					</div>
					<div class="mt-1 d-flex justify-content-between">
						<p v-on:click="seleccionar_todos()" class="btn btn-primary" id="id_select_all">Seleccionar todos</p>
						<p v-on:click="eliminar_todos()" class="btn btn-secondary" id="id_reset">Eliminar selección</p>
					</div>

					<button class="btn btn-lg btn-primary btn-block mt-3" type="submit">Crear evento</button>
				</form>
			</div>
		</div>
		
	</div>
</div>

<script>
    let vue = new Vue({
        el:'#id_app',
        delimiters:["[[","]]"],
        data: {
            select_all_btn: $('#id_select_all'),
            reset_btn: $('#id_reset'),
			select_multiple: '',
        },
		mounted() {
			this.select_multiple = new Choices('#id_participantes', {
				searchFloor: 3,
				itemSelectText: 'Pulsa para seleccionar',
				removeItemButton: true,
				searchPlaceholderValue: "Buscar amigos",
				noResultsText: 'No se encontraron resultados',
				noChoicesText: "No choices to choose from",
			});
		},
		methods: {
			seleccionar_todos() {
				opciones = document.getElementsByClassName('choices__item')
				for (let i = 0; i < opciones.length; i++) {
					this.select_multiple.setChoiceByValue(opciones[i].dataset.value)		
				}
			},
			eliminar_todos() {
				this.select_multiple.removeActiveItems()
			}
		}
    })
</script>

{% endblock content %}

gameofskate_venv/src/eventos/templates/eventos/evento.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	.profile-image {
		object-fit: cover;
		border-radius: 50%;
		height: 100px;
		width: 100px;
	}
    .perfil-link{
        color: #000;
    }
    .trick-gif{
        object-fit: cover;
		border-radius: 50%;
		height: 100px;
		width: 100px;
    }
    .card-header{
        background-color: lightgrey;
    }
	.separador{
        border-bottom: 1px solid black;
    }
</style>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>


<div class="container" id="id_app">
    <div class="card">
        <div class="card-body">
            <h2 class="card-header mb-3 text-center">{{evento.nombre}}</h2>
            <h3>Descripción</h3>
            <div class="container mb-3">
                <p class="card-text">{{evento.descripcion}}</p>
            </div>

            <h3>Participantes</h3>
            <div class="container">
                <div class="row">
                    {% for participante in participantes %}
                    <div class="col-6 mb-3">
                        <a class="perfil-link" href="{% url 'cuenta:view' user_id=participante.pk %}">
                            <img class="profile-image" src="{{participante.profile_image.url}}" alt="Foto de perfil">
                            <h4 class="m-3">{{participante.username|truncatechars:30}}</h4>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>

		    {% if evento.finalizado %}
            <div class="container-fliud separador my-5"></div>
            <div class="row">
                <div class="col-6">
                    <h3>Ganador</h3>
                    <div class="container">
		                {% if evento.ganador %}
                        <a class="perfil-link d-flex flex-grow-1 flex-row flex-wrap align-items-center" href="{% url 'cuenta:view' user_id=evento.ganador.pk %}">
                            <img class="profile-image" src="{{evento.ganador.profile_image.url}}" alt="Foto de perfil">
                            <h4 class="ml-3">{{evento.ganador.username|truncatechars:30}}</h4>
                        </a>
		                {% else %}
                        <div class="perfil-link d-flex flex-grow-1 flex-row flex-wrap align-items-center">
                            <img class="profile-image" src="{% static 'gameofskate/logo_250_250_transparent.png' %}" alt="Foto de perfil usuario eliminado">
                            <h4 class="ml-3">Usuario eliminado</h4>
                        </div>
		                {% endif %}
                    </div>
                </div>
                <div class="col-6">
                    <h3>Best Trick</h3>
                    <div class="container d-flex align-items-center">

                        <img v-if="this.trick == '360flip' || this.trick == '360 flip' | this.trick == 'treflip'" class="trick-gif" src="../../../static/gameofskate/360flip_trick.gif" alt="Gif de un truco">
                        <img v-if="this.trick == 'bsflip' || this.trick == 'bs flip' | this.trick == 'backside flip'" class="trick-gif" src="../../../static/gameofskate/bsflip_trick.gif" alt="Gif de un truco">

                        <h4 class="ml-3" id="id_best_trick">{{evento.best_trick|truncatechars:30}}</h4>
                    </div>
                </div>
            </div>

		    {% elif evento.en_curso %}
		        {% if es_creador or user.is_admin %}
            <form class="form-finalizar-evento" method="post" id="id_form_finalizar">{% csrf_token %}
                <div class="d-flex">
                    <div class="container-fluid">
                        <label for="id_gandor">Ganador:</label>
                        <select class="form-control" name="ganador" id="id_ganador" placeholder="Ganador" required>
                            {% for participante in participantes %}
                            <option value="{{participante.pk}}">{{participante.username}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="container-fluid ml-2">
                        <label for="id_best_trick_form">Best Trick:</label>
                        <input type="text" name="best_trick" id="id_best_trick_form" class="form-control" placeholder="Mejor truco del ganador">
                    </div>
                </div>
                <div class="container">
                    <button class="btn btn-primary mt-3" id="id_submit" type="submit">Finalizar evento</button>
                </div>
            </form>
		        {% endif %}

		    {% else %}
		        {% if es_creador or user.is_admin %}
            <div class="mt-5">
                {% if num_invitaciones_pendientes > 0 %}
                <p>Invitaciones que aún no han sido aceptadas: {{num_invitaciones_pendientes}}</p>
                <p>Asegúrate de que todos los participantes han aceptado su invitación antes de dar el evento por comenzado.</p>
		        {% elif num_invitaciones_pendientes == 0 %}
                <p>Todos los participantes han aceptado su invitación.</p>
		        {% endif %}
                <a class="btn btn-primary" id="id_comenzar" href="{% url 'eventos:comenzar-evento' evento_id=evento.id %}">COMENZAR EVENTO</a>
            </div>
		        {% endif %}

		    {% endif %}

            {% if es_creador or user.is_admin %}
            <div class="d-flex justify-content-end mt-5">
                <a class="btn btn-danger" id="id_eliminar" href="{% url 'eventos:eliminar-evento' evento_id=evento.id %}">Eliminar evento</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>


<script>
    let vue = new Vue({
        el:'#id_app',
        delimiters:["[[","]]"],
        data: {
            trick: $('#id_best_trick').text().toLowerCase(),
        },
    })
</script>

<script>
    $('#id_submit').confirm({
        title: 'Confirmación',
        content: '¿Estás seguro de que quieres finalizar el evento?',
        type: 'dark',
        buttons: {
            confirmar: {
                text: 'Confirmar',
                btnClass: 'btn-blue',
                action: function(){
                    $('#id_form_finalizar').submit();
                    location.reload();
                }
            },
            cancelar: function () {
                // pass
            },
        }
    });

    $('#id_comenzar').confirm({
        title: 'Confirmación',
        content: '¿Estás seguro de que quieres comenzar el evento?',
        type: 'dark',
        buttons: {
            confirmar: {
                text: 'Confirmar',
                btnClass: 'btn-blue',
                action: function(){
                    window.location.href = $('#id_comenzar').attr('href');
                }
            },
            cancelar: function () {
                // pass
            },
        }
    });

    $('#id_eliminar').confirm({
        title: 'Confirmación',
        content: '¿Estás seguro de que quieres eliminar el evento?',
        type: 'red',
        buttons: {
            confirmar: {
                text: 'Confirmar',
                btnClass: 'btn-blue',
                action: function(){
                    window.location.href = $('#id_eliminar').attr('href');
                }
            },
            cancelar: function () {
                // pass
            },
        }
    });
</script>


{% endblock content %}

gameofskate_venv/src/eventos/templates/eventos/lista_eventos.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	.profile-image {
		object-fit: cover;
		border-radius: 50%;
		height: 100px;
		width: 100px;
	}
    .perfil-link{
        color: #000;
    }
    .evento-container{
        border: 1px solid black;
        border-radius: 10px;
    }
    .card-header{
        background-color: lightgrey;
    }

    @media (max-width: 450px) {  
        h2 {font-size:1.1rem;}
        h3 {font-size:.6rem;}
        h4 {font-size:.55rem; overflow-wrap: normal;}
        p {font-size:.4rem;}
        .profile-image {
            height: 50px;
            width: 50px;
        }
    }
    @media (max-width: 652px) and (min-width: 450px) {  
        h2 {font-size:1.3rem;}
        h3 {font-size:.8rem;}
        h4 {font-size:.7rem;  overflow-wrap: normal;}
        p {font-size:.6rem;}
        .profile-image {
            height: 60px;
            width: 60px;
        }
    }
    @media (max-width: 768px) and (min-width: 652px) {  
        h2 {font-size:1.6rem;}
        h3 {font-size:1.3rem;}
        h4 {font-size:1rem; overflow-wrap: normal;}
        p {font-size:.8rem;}
        .profile-image {
            height: 75px;
            width: 75px;
        }
    }
</style>

<div class="container">
	<div class="card p-2">

		{% if eventos_en_curso %}
        <div class="card-body">
            <div class="card-header mb-3">
                <h2>Eventos en curso</h2>
            </div>
            <div class="container">
                <div class="row">
                    <h3 class="col-6">Creador</h3>
                    <h3 class="col-6">Información del evento</h3>
                </div>
                {% for evento in eventos_en_curso %}
                <div class="row evento-container p-3">
                    <div class="col-6 creador-wrapper">
                        <a class="perfil-link" href="{% url 'cuenta:view' user_id=evento.creador.pk %}">
                            <img class="profile-image" src="{{evento.creador.profile_image.url}}" alt="Foto de perfil">
                            <h4 class="m-3">{{evento.creador.username|truncatechars:30}}</h4>
                        </a>
                    </div>
                    <div class="col-6 evento-wrapper">
                        <a class="perfil-link d-flex flex-column" href="{% url 'eventos:evento-view' evento_id=evento.id %}">
                            <h4 class="card-title">{{evento.nombre|truncatechars:30}}</h4>
                            <p class="card-title">{{evento.descripcion|truncatechars:140}}</p>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
		{% endif %}
		{% if eventos_pendientes %}
        <div class="card-body">
            <div class="card-header mb-3">
                <h2>Eventos pendientes</h2>
            </div>
            <div class="container">
                <div class="row">
                    <h3 class="col-6">Creador</h3>
                    <h3 class="col-6">Información del evento</h3>
                </div>
                {% for evento in eventos_pendientes %}
                <div class="row evento-container p-3">
                    <div class="col-6 creador-wrapper">
                        <a class="perfil-link" href="{% url 'cuenta:view' user_id=evento.creador.pk %}">
                            <img class="profile-image" src="{{evento.creador.profile_image.url}}" alt="Foto de perfil">
                            <h4 class="m-3">{{evento.creador.username|truncatechars:30}}</h4>
                        </a>
                    </div>
                    <div class="col-6 evento-wrapper">
                        <a class="perfil-link d-flex flex-column" href="{% url 'eventos:evento-view' evento_id=evento.id %}">
                            <h4 class="card-title">{{evento.nombre|truncatechars:30}}</h4>
                            <p class="card-title">{{evento.descripcion|truncatechars:140}}</p>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
		{% endif %}
        {% if eventos_finalizados %}
        <div class="card-body">
            <div class="card-header mb-3">
                <h2>Eventos Finalizados</h2>
            </div>
            <div class="container">
                <div class="row">
                    <h3 class="col-3">Creador</h3>
                    <h3 class="col-6">Información del evento</h3>
                    <h3 class="col-3">Ganador</h3>
                </div>
                {% for evento in eventos_finalizados %}
                <div class="row evento-container p-3">
                    <div class="col-3 creador-wrapper">
                        <a class="perfil-link" href="{% url 'cuenta:view' user_id=evento.creador.pk %}">
                            <img class="profile-image" src="{{evento.creador.profile_image.url}}" alt="Foto de perfil">
                            <h4 class="m-3">{{evento.creador.username|truncatechars:30}}</h4>
                        </a>
                    </div>
                    <div class="col-6 evento-wrapper">
                        <a class="perfil-link d-flex flex-column" href="{% url 'eventos:evento-view' evento_id=evento.id %}">
                            <h4 class="card-title">{{evento.nombre|truncatechars:30}}</h4>
                            <p class="card-title">{{evento.descripcion|truncatechars:140}}</p>
                        </a>
                    </div>
                    <div class="col-3 ganador-wrapper">
		                {% if evento.ganador %}
                        <a class="perfil-link" href="{% url 'cuenta:view' user_id=evento.ganador.pk %}">
                            <img class="profile-image" src="{{evento.ganador.profile_image.url}}" alt="Foto de perfil">
                            <h4 class="m-3">{{evento.ganador.username|truncatechars:30}}</h4>
                        </a>
                        {% else %}
                        <div class="perfil-link d-flex flex-grow-1 flex-row flex-wrap align-items-center">
                            <img class="profile-image" src="{% static 'gameofskate/logo_250_250_transparent.png' %}" alt="Foto de perfil usuario eliminado">
                            <h4 class="ml-3">Usuario eliminado</h4>
                        </div>
		                {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
		{% endif %}

        {% if not eventos_en_curso and not eventos_pendientes and not eventos_finalizados %}
		<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
			<p>No se encontraron eventos.</p>
		</div>
		{% endif %}
		</div>
	</div>
	
</div>

{% endblock content %}