gameofskate_venv/src/GameOfSkate/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from personal.views import (
	no_login_view
)

from cuenta.views import (
    register_view,
    login_view,
    logout_view,
    buscar_usuarios_view,
)

urlpatterns = [
	path('', no_login_view, name='home'),
    path('cuenta/', include('cuenta.urls', namespace='cuenta')),
	path('admin/', admin.site.urls),
    path('amistad/', include('amistad.urls', namespace='amistad')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', register_view, name="register"),
    path('buscar/', buscar_usuarios_view, name="buscar"),
    path('eventos/', include('eventos.urls', namespace='eventos')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gameofskate_venv/src/amistad/urls.py
from django.urls import path

from amistad.views import(
	enviar_solicitud_amistad,
	solicitudes_amistad,
	aceptar_solicitud_amistad,
	eliminar_amigo,
	rechazar_solicitud_amistad,
	cancelar_solicitud_amistad,
	lista_amigos_view,
)

app_name = 'amistad'

urlpatterns = [
	path('lista_amigos/<user_id>', lista_amigos_view, name='lista-amigos'),
	path('eliminar_amigo/', eliminar_amigo, name='eliminar-amigo'),
    path('enviar_solicitud_amistad/', enviar_solicitud_amistad, name='enviar-solicitud-amistad'),
    path('cancelar_solicitud_amistad/', cancelar_solicitud_amistad, name='cancelar-solicitud-amistad'),
    path('solicitudes_amistad/<user_id>/', solicitudes_amistad, name='solicitudes-amistad'),
    path('aceptar_solicitud_amistad/<solicitud_amistad_id>/', aceptar_solicitud_amistad, name='aceptar-solicitud-amistad'),
    path('rechazar_solicitud_amistad/<solicitud_amistad_id>/', rechazar_solicitud_amistad, name='rechazar-solicitud-amistad'),
]

gameofskate_venv/src/cuenta/urls.py
from django.urls import path

from cuenta.views import (
	cuenta_view,
	editar_cuenta_view,
	eliminar_cuenta,
)

app_name = 'cuenta'

urlpatterns = [
	path('<user_id>/', cuenta_view, name="view"),
	path('<user_id>/editar/', editar_cuenta_view, name="editar"),
	path('eliminar_cuenta/<user_id>/', eliminar_cuenta, name='eliminar-cuenta'),
]

gameofskate_venv/src/eventos/urls.py
from django.urls import path

from eventos.views import(
	crear_evento,
	solicitudes_eventos,
	aceptar_solicitud_evento,
	rechazar_solicitud_evento,
	lista_eventos_view,
	evento_view,
	comenzar_evento,
	eliminar_evento,
)

app_name = 'eventos'
urlpatterns = [
	path('crear_evento/', crear_evento, name='crear-evento'),
	path('lista_eventos/<user_id>', lista_eventos_view, name='lista-eventos'),
    path('solicitudes_eventos/<user_id>/', solicitudes_eventos, name='solicitudes-eventos'),
    path('aceptar_solicitud_evento/<solicitud_evento_id>/', aceptar_solicitud_evento, name='aceptar-solicitud-evento'),
    path('rechazar_solicitud_evento/<solicitud_evento_id>/', rechazar_solicitud_evento, name='rechazar-solicitud-evento'),
    path('evento/<evento_id>/', evento_view, name='evento-view'),
    path('comenzar_evento/<evento_id>/', comenzar_evento, name='comenzar-evento'),
	path('eliminar_evento/<evento_id>/', eliminar_evento, name='eliminar-evento'),
]

gameofskate_venv/src/cuenta/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.files.storage import FileSystemStorage
from django.conf import settings
import os


class MyAccountManager(BaseUserManager):
	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError('Debes añadir una dirección de email')
		if not username:
			raise ValueError('Debes añadir una nombre de usuario')

		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)

		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, password):
		user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
		)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user


def get_profile_image_filepath(self, filename):
	return 'profile_images/' + str(self.pk) + '/profile_image.png'

def get_default_profile_image():
	return "gameofskate/default_profile_image.png"


class Cuenta(AbstractBaseUser):
	email 					= models.EmailField(verbose_name="email", max_length=60, unique=True)
	username 				= models.CharField(max_length=30, unique=True)
	date_joined				= models.DateTimeField(verbose_name='date joined', auto_now_add=True)
	last_login				= models.DateTimeField(verbose_name='last login', auto_now=True)
	is_admin				= models.BooleanField(default=False)
	is_active				= models.BooleanField(default=True)
	is_staff				= models.BooleanField(default=False)
	is_superuser			= models.BooleanField(default=False)
	profile_image			= models.ImageField(max_length=255, upload_to=get_profile_image_filepath, null=True, blank=True, default=get_default_profile_image)
	hide_email				= models.BooleanField(default=True)

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username']

	objects = MyAccountManager()

	def __str__(self):
		return self.username

	def get_profile_image_filename(self):
		return str(self.profile_image)[str(self.profile_image).index('profile_images/' + str(self.pk) + "/"):]

	def has_perm(self, perm, obj=None):
		return self.is_admin

	def has_module_perms(self, app_label):
		return True

	def eliminar(self):
		self.delete()

gameofskate_venv/src/cuenta/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from cuenta.models import Cuenta


class RegistrationForm(UserCreationForm):
	email = forms.EmailField(max_length=254, help_text='Escribe una dirección de email válida.')

	class Meta:
		model = Cuenta
		fields = ('email', 'username', 'password1', 'password2', )

	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		try:
			cuenta = Cuenta.objects.exclude(pk=self.instance.pk).get(email=email)
		except Cuenta.DoesNotExist:
			return email
		raise forms.ValidationError('El email "%s" ya está en uso.' % cuenta)

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			cuenta = Cuenta.objects.exclude(pk=self.instance.pk).get(username=username)
		except Cuenta.DoesNotExist:
			return username
		raise forms.ValidationError('El nombre de usuario "%s" ya está en uso.' % username)


class CuentaAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Contraseña', widget=forms.PasswordInput)

	class Meta:
		model = Cuenta
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Login no válido")


class ActualizarCuentaForm(forms.ModelForm):

    class Meta:
        model = Cuenta
        fields = ('username', 'email', 'profile_image', 'hide_email' )

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            cuenta = Cuenta.objects.exclude(pk=self.instance.pk).get(email=email)
        except Cuenta.DoesNotExist:
            return email
        raise forms.ValidationError('El email "%s" ya está en uso.' % cuenta)

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            cuenta = Cuenta.objects.exclude(pk=self.instance.pk).get(username=username)
        except Cuenta.DoesNotExist:
            return username
        raise forms.ValidationError('El nombre de usuario "%s" ya está en uso.' % username)


    def save(self, commit=True):
        cuenta = super(ActualizarCuentaForm, self).save(commit=False)
        cuenta.username = self.cleaned_data['username']
        cuenta.email = self.cleaned_data['email'].lower()
        cuenta.profile_image = self.cleaned_data['profile_image']
        cuenta.hide_email = self.cleaned_data['hide_email']
        if commit:
            cuenta.save()
        return cuenta

gameofskate_venv/src/cuenta/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate, logout
from django.conf import settings

from django.core.files.storage import default_storage
from django.core.files.storage import FileSystemStorage
from django.core import files
import os
import base64
import json

from cuenta.forms import RegistrationForm, CuentaAuthenticationForm, ActualizarCuentaForm
from cuenta.models import Cuenta
from amistad.utils import get_solicitudes_amistad
from amistad.estado_solicitud_amistad import EstadoSolicitudAmistad
from amistad.models import ListaAmigos, SolicitudAmistad

from eventos.utils import get_solicitudes_evento
from eventos.estado_solicitud_evento import EstadoSolicitudEvento
from eventos.models import ListaEventos, SolicitudEvento


TEMP_PROFILE_IMAGE_NAME = "temp_profile_image.png"


def buscar_usuarios_view(request, *args, **kwargs):
	user = request.user
	if user.is_authenticated:
		context = {}
		if request.method == "GET":
			busqueda = request.GET.get("q")
			if len(busqueda) > 0:
				resultados = Cuenta.objects.filter(email__icontains=busqueda).filter(username__icontains=busqueda).distinct()
				cuentas = []
				lista_amigos = ListaAmigos.objects.get(user=user)
				for cuenta in resultados:
					cuentas.append((cuenta, lista_amigos.son_amigos(cuenta)))
				context['cuentas'] = cuentas
	else:
		return redirect("login")
				
	return render(request, "cuenta/resultados_busqueda.html", context)



def register_view(request, *args, **kwargs):
	user = request.user
	if user.is_authenticated: 
		return HttpResponse("Ya estás autenticado como " + str(user.email))

	context = {}
	if request.POST:
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			email = form.cleaned_data.get('email').lower()
			raw_password = form.cleaned_data.get('password1')
			cuenta = authenticate(email=email, password=raw_password)
			login(request, cuenta)
			destino = kwargs.get("next")
			if destino:
				return redirect(destino)
			return redirect('home')
		else:
			context['registration_form'] = form

	else:
		form = RegistrationForm()
		context['registration_form'] = form
	return render(request, 'cuenta/register.html', context)


def logout_view(request):
	logout(request)
	return redirect("home")


def login_view(request, *args, **kwargs):
	context = {}

	user = request.user
	if user.is_authenticated: 
		return redirect("home")

	destino = get_redirect_if_exists(request)

	if request.POST:
		form = CuentaAuthenticationForm(request.POST)
		if form.is_valid():
			email = request.POST['email']
			password = request.POST['password']
			user = authenticate(email=email, password=password)

			if user:
				login(request, user)
				if destino:
					return redirect(destino)
				return redirect("home")

	else:
		form = CuentaAuthenticationForm()

	context['login_form'] = form

	return render(request, "cuenta/login.html", context)


def get_redirect_if_exists(request):
	redirect = None
	if request.GET:
		if request.GET.get("next"):
			redirect = str(request.GET.get("next"))
	return redirect


def cuenta_view(request, *args, **kwargs):
	user = request.user
	if user.is_authenticated:
		context = {}
		user_id = kwargs.get("user_id")
		try:
			cuenta = Cuenta.objects.get(pk=user_id)
		except:
			return HttpResponse("Algo ha ido mal.")
		if cuenta:
			context['id'] = cuenta.id
			context['username'] = cuenta.username
			context['email'] = cuenta.email
			context['profile_image'] = cuenta.profile_image.url
			context['hide_email'] = cuenta.hide_email

			try:
				lista_amigos = ListaAmigos.objects.get(user=cuenta)
			except ListaAmigos.DoesNotExist:
				lista_amigos = ListaAmigos(user=cuenta)
				lista_amigos.save()
			amigos = lista_amigos.amigos.all()
			context['amigos'] = amigos

			try:
				lista_eventos = ListaEventos.objects.get(user=cuenta)
			except ListaEventos.DoesNotExist:
				lista_eventos = ListaEventos(user=cuenta)
				lista_eventos.save()
			eventos = lista_eventos.eventos.all()
			context['eventos'] = eventos
		
			is_self = True
			is_friend = False
			solicitud_amistad_enviada = EstadoSolicitudAmistad.NO_SOLICITUD.value
			solicitudes_amistad = None
			solicitud_evento_enviada = EstadoSolicitudEvento.NO_SOLICITUD.value
			solicitudes_evento = None
			if user != cuenta:
				is_self = False
				if amigos.filter(pk=user.id):
					is_friend = True
					if get_solicitudes_evento(remitente=cuenta, destinatario=user) != False:
						solicitud_evento_enviada = EstadoSolicitudEvento.SOLICITUD_RECIBIDA.value
						context['solicitud_evento_pendiente_id'] = get_solicitudes_evento(remitente=cuenta, destinatario=user).id
					elif get_solicitudes_evento(remitente=user, destinatario=cuenta) != False:
						solicitud_evento_enviada = EstadoSolicitudEvento.SOLICITUD_ENVIADA.value
					else:
						solicitud_evento_enviada = EstadoSolicitudEvento.NO_SOLICITUD.value
				else:
					is_friend = False
					if get_solicitudes_amistad(remitente=cuenta, destinatario=user) != False:
						solicitud_amistad_enviada = EstadoSolicitudAmistad.SOLICITUD_RECIBIDA.value
						context['solicitud_amistad_pendiente_id'] = get_solicitudes_amistad(remitente=cuenta, destinatario=user).id
					elif get_solicitudes_amistad(remitente=user, destinatario=cuenta) != False:
						solicitud_amistad_enviada = EstadoSolicitudAmistad.SOLICITUD_ENVIADA.value
					else:
						solicitud_amistad_enviada = EstadoSolicitudAmistad.NO_SOLICITUD.value
			else:
				try:
					solicitudes_amistad = SolicitudAmistad.objects.filter(destinatario=user, is_active=True)
					solicitudes_evento = SolicitudEvento.objects.filter(destinatario=user, is_active=True)
				except:
					pass
				
			context['is_self'] = is_self
			context['is_friend'] = is_friend
			context['solicitud_amistad_enviada'] = solicitud_amistad_enviada
			context['solicitudes_amistad'] = solicitudes_amistad
			context['solicitud_evento_enviada'] = solicitud_evento_enviada
			context['solicitudes_evento'] = solicitudes_evento
			context['BASE_URL'] = settings.BASE_URL
	else:
		return redirect("login")

	return render(request, "cuenta/cuenta.html", context)


def editar_cuenta_view(request, *args, **kwargs):
	user = request.user
	if  user.is_authenticated:
		user_id = kwargs.get("user_id")
		cuenta = Cuenta.objects.get(pk=user_id)
		if cuenta.pk != user.pk and not user.is_admin:
			return HttpResponse("No puedes editar el perfil de otra persona.")
		context = {}
		if request.POST:
			form = ActualizarCuentaForm(request.POST, request.FILES, instance=cuenta)
			if form.is_valid():
				form.save()
				return redirect("cuenta:view", user_id=cuenta.pk)
			else:
				form = ActualizarCuentaForm(request.POST, instance=cuenta,
					initial={
						"id": cuenta.pk,
						"email": cuenta.email, 
						"username": cuenta.username,
						"profile_image": cuenta.profile_image,
						"hide_email": cuenta.hide_email,
					}
				)
				context['form'] = form
		else:
			form = ActualizarCuentaForm(
				initial={
						"id": cuenta.pk,
						"email": cuenta.email, 
						"username": cuenta.username,
						"profile_image": cuenta.profile_image,
						"hide_email": cuenta.hide_email,
					}
				)
			context['form'] = form
		context['user_id'] = user_id
	else:
		return redirect("login")
		
	return render(request, "cuenta/editar_cuenta.html", context)


def eliminar_cuenta(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated:
        user_id = kwargs.get('user_id')
        cuenta = Cuenta.objects.get(id=user_id)
        cuenta.eliminar()
    else:
        return redirect("login")
        
    return redirect("home")

gameofskate_venv/src/cuenta/templates/cuenta/cuenta.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	.imagen-container{
		max-width: 250px;
		height: auto;
	}
	.profile-image {
		object-fit: cover;
		border-radius: 50%;
		height: 250px;
		width: 250px;
	}
	.campo-heading{
		color: var(--secondary-text-color);
	}
	.icono-container:hover {
		cursor: pointer;
		opacity: 0.3;
	}
	.amigos-icono{
		color: #4287f5;
		font-size: 40px;
	}
	.anadir-amigo-icono{
		color: #4287f5;
		font-size: 40px;
	}
	.amigos-text{
		font-weight: 500;
		color: black;
	}
	.amigos-btn{
		background-color: #cccccc;
		border-color: #cccccc;
		color: #000;
		font-weight: 500;
	}
	.amigos-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.card{
		border-radius: 12px;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
	.aceptar-solicitud-amistad{
		color: green;
	}
	.aceptar-solicitud-amistad:hover {
		opacity: 0.3;
	}
	.rechazar-solicitud-amistad:hover {
		opacity: 0.3;
	}
	.rechazar-solicitud-amistad{
		color: red;
	}
</style>

<div class="container-fluid">
	<div class="d-flex flex-row justify-content-center flex-wrap align-items-start">

		<div class="card profile-card m-2">
		  <div class="card-body">
		  	<div class="d-flex flex-column justify-content-center p-4">
		  		<div class="imagen-container mx-auto mb-4">
		  			<img class="d-block border border-dark rounded-circle img-fluid mx-auto profile-image" alt="foto de perfil" id="id_profile_image" src="{{profile_image}}">
		  		</div>
		  		<p class="mt-4 mb-1 campo-heading">Email</p>
		  		{%  if is_self or user.is_admin %}
		  			<h5>{{email}}</h5>
		  		{% else %}
		  			{% if hide_email %}
			  			<h5>**********</h5>
			  		{% else %}
			  			<h5>{{email}}</h5>
			  		{% endif %}
			  	{% endif %}
		  		<p class="mt-4 mb-1 campo-heading">Username</p>
		  		<h5>{{username}}</h5>

		  		{% if is_self or user.is_admin %}
		  		<a  class="mt-4 btn btn-primary" href="{% url 'cuenta:editar' user_id=id %}">Actualizar</a>
		  		{% endif %}
		  	</div>
		  </div>
		</div>

		{% if request.user.is_authenticated %}
		<div class="d-flex flex-column mb-4">

			{% if solicitud_amistad_enviada == 0 %}
			<div class="card m-2 p-4">
				<div class="d-flex flex-row align-items-center">
					<span class="amigo-text align-items-center mr-2">Aceptar Solicitud de Amistad</span>
					<span id="id_cancelar_{{id}}" class="rechazar-solicitud-amistad material-icons p-1" onclick='triggerRechazarSolicitudAmistad("{{solicitud_amistad_pendiente_id}}")'>cancel</span>
  					<span id="id_confirmar_{{id}}" class="aceptar-solicitud-amistad material-icons p-1" onclick='triggerAceptarSolicitudAmistad("{{solicitud_amistad_pendiente_id}}")'>check</span>
				</div>
			</div>
			{% endif %}

			<div class="card m-2 px-4 pb-4">
				{% if is_friend == False and is_self == False %}
					{% if solicitud_amistad_enviada == 1 %}
					<div class="d-flex flex-column align-items-center pt-4">
						<button class="btn btn-danger" id="id_cancelar_solicitud_amistad_btn">
							Cancelar solicitud de amistad
						</button>
					</div>
					{% endif %}
					{% if solicitud_amistad_enviada == -1 %}
					<div class="d-flex flex-column align-items-center pt-4">
						<button class="btn btn-primary" id="id_enviar_solicitud_amistad_btn">
							Enviar solicitud de amistad
						</button>
					</div>
					{% endif %}
				{% endif %}
					
				{% if is_friend %}
					<div class="dropdown pt-4 m-auto">
						<button class="btn btn-secondary dropdown-toggle amigos-btn" type="button" id="id_amigos_toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Amigos
						</button>
						<div class="dropdown-menu" aria-labelledby="id_amigos_toggle">
							<a class="dropdown-item" href="#" onclick="eliminarAmigo('{{id}}', onAmigoEliminado)">Eliminar amigo</a>
						</div>
					</div>
				{% endif %}
				
		  		<div class="d-flex flex-column pt-4">
					<a href="{% url 'amistad:lista-amigos' user_id=id %}">
						<div class="d-flex flex-row align-items-center justify-content-center icono-container">
							<span class="material-icons mr-2 amigos-icono">contact_page</span><span class="amigos-text">Amigos ({{amigos|length}})</span>
						</div>
					</a>
				</div>

				<div class="d-flex flex-column pt-4">
					<a href="{% url 'eventos:lista-eventos' user_id=id %}">
						<div class="d-flex flex-row align-items-center justify-content-center icono-container">
							<span class="material-icons mr-2 amigos-icono">skateboarding</span><span class="amigos-text">Eventos ({{eventos|length}})</span>
						</div>
					</a>
				</div>

			</div>

			{% if is_self %}
			<a  class="mt-4 btn btn-primary" href="{% url 'eventos:crear-evento' %}">CREAR EVENTO</a>
			{% endif %}

			{% if solicitudes_amistad %}
			<div class="card m-2 px-4 pb-4">
		  		<div class="d-flex flex-column pt-4">
					<a href="{% url 'amistad:solicitudes-amistad' user_id=id %}">
						<div class="d-flex flex-row align-items-center justify-content-center icono-container">
							<span class="material-icons mr-2 anadir-amigo-icono">person_add</span><span class="amigos-text">Solicitudes de amistad ({{solicitudes_amistad|length}})</span>
						</div>
					</a>
				</div>
			</div>
			{% endif %}

			{% if solicitudes_evento %}
			<div class="card m-2 px-4 pb-4">
		  		<div class="d-flex flex-column pt-4">
					<a href="{% url 'eventos:solicitudes-eventos' user_id=id %}">
						<div class="d-flex flex-row align-items-center justify-content-center icono-container">
							<span class="material-icons mr-2 anadir-amigo-icono">group_add</span><span class="amigos-text">Invitaciones a eventos ({{solicitudes_evento|length}})</span>
						</div>
					</a>
				</div>
			</div>
			{% endif %}
			
		</div>
		{% endif %}

		
	</div>
</div>


<script type="text/javascript">

	function onSolicitudAmistadEnviada(){
		location.reload();
	}

	function onSolicitudAmistadCancelada(){
		location.reload();
	}

	function onAmigoEliminado(){
		location.reload();
	}

	function onSolicitudAmistadAceptada(){
		location.reload();
	}

	function onSolicitudAmistadRechazada(){
		location.reload();
	}


	var enviarSolicitudAmistadBtn = document.getElementById("id_enviar_solicitud_amistad_btn")
	if (enviarSolicitudAmistadBtn != null){
		enviarSolicitudAmistadBtn.addEventListener("click", function(){
			enviarSolicitudAmistad("{{id}}", onSolicitudAmistadEnviada)
		})
	}

	var cancelarSolicitudAmistadBtn = document.getElementById("id_cancelar_solicitud_amistad_btn")
	if(cancelarSolicitudAmistadBtn != null){
		cancelarSolicitudAmistadBtn.addEventListener("click", function(){
			cancelarSolicitudAmistad("{{id}}", onSolicitudAmistadCancelada)
		})
	}

	var eliminarAmigoBtn = document.getElementById("id_eliminar_amigo_btn")
	if (eliminarAmigoBtn != null){
		eliminarAmigoBtn.addEventListener("click", function(){
			eliminarAmigo("{{id}}", onAmigoEliminado)
		})
	}

	function triggerAceptarSolicitudAmistad(solicitud_amistad_id){
		aceptarSolicitudAmistad(solicitud_amistad_id, onSolicitudAmistadAceptada)
	}

	function triggerRechazarSolicitudAmistad(solicitud_amistad_id){
		rechazarSolicitudAmistad(solicitud_amistad_id, onSolicitudAmistadRechazada)
	}
	
</script>

{% include 'amistad/snippets/enviar_solicitud_amistad.html' %}
{% include 'amistad/snippets/aceptar_solicitud_amistad.html' %}
{% include 'amistad/snippets/rechazar_solicitud_amistad.html' %}
{% include 'amistad/snippets/cancelar_solicitud_amistad.html' %}
{% include 'amistad/snippets/eliminar_amigo.html' %}

{% endblock content %}

gameofskate_venv/src/cuenta/templates/cuenta/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	.form-login input[type="email"] {
		margin-bottom: 10px;
		border-bottom-right-radius: 0;
		border-bottom-left-radius: 0;
	}
	.form-login input[type="password"] {
		margin-bottom: -1px;
		border-top-left-radius: 0;
		border-top-right-radius: 0;
	}

	.card-login {
		width: 100%;
		max-width: 400px;
		padding: 15px;
		margin: auto;
	}
</style>

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card card-login">
		  	<div class="card-body">
				<form class="form-login" method="post">{% csrf_token %}
					<div class="d-flex flex-column pb-3">
						<img class="img-fluid mx-auto d-block" src="{% static 'gameofskate/logo_250_250_transparent.png' %}" alt="foto de perfil" width="250" height="250">
					</div>
					<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email" required autofocus>

					<input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>

					{% for field in login_form %}
					<p>
						{% for error in field.errors %}
						<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
					{% endfor %}
					{% if login_form.non_field_errors %}
					<div style="color: red">
						<p>{{login_form.non_field_errors}}</p>
					</div>
					{% endif %}

					<button class="btn btn-lg btn-primary btn-block" type="submit">Iniciar sesión</button>
				</form>
		  	</div>
		</div>
	</div>
</div>

{% endblock content %}